title: "<LeeHuwuj/>"
email: leehuwuj@gmail.com
author: leehuwuj
copyright: "Unpublished Work (cleft) 2021-{currentYear} {author}"

description: >-
  Diligent, Fun and Friendly. Sharing my thoughts and experiences in software development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huu.dev"
sitemap: true
theme_color: snowwhite
night_mode: "off"
# header_transparent: true
header_pages:
  - index.html
  - tags.html
  - categories.html

# Page default value
defaults:
  home:
    heading: "Huu Le"
    subheading: "Diligent, Fun and Friendly"

yat:
  date_format: "%Y-%m-%d"

google_analytics: G-NNXMJSV65Q
enableDNT: "false"

markdown: kramdown
kramdown:
  input: GFM

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

# disqus:
#   shortname: my_disqus_shortname
