title: "<LeeHuwuj/>"
email: leehuwuj@gmail.com
author: leehuwuj
copyright: "Unpublished Work (cleft) 2021-{currentYear} {author}"

description: >-
  Diligent, Fun and Friendly. Sharing my thoughts and experiences in software development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huu.dev"
sitemap: true
theme_color: snowwhite
night_mode: "off"
# header_transparent: true
header_pages:
  - index.html
  - tags.html
  - categories.html

# Page default value
defaults:
  home:
    heading: "Huu Le"
    subheading: "Diligent, Fun and Friendly"

banner:
  video: null             # Video banner source
  loop: true              # Video loop
  volume: 0               # Video volume (100% is 1.0)
  start_at: 0             # Video start time
  image: "http://huu.dev/images/banner.png"             # Image banner source
  opacity: 0.4            # Banner opacity (100% is 1.0)
  background: "rgba(0, 0, 0, 0.5)"  # Banner background (Could be a image)
  height: "640px"         # Banner default height
  min_height: null        # Banner minium height
  heading_style: "font-weight: bold;"     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
  subheading_style: "font-weight: bold;"  # Custom subheading style (e.g. color: gold)

yat:
  date_format: "%Y-%m-%d"

google_analytics: G-NNXMJSV65Q
enableDNT: "false"

markdown: kramdown
kramdown:
  input: GFM

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

# disqus:
#   shortname: my_disqus_shortname
